# -*- coding: utf-8 -*-
"""Workshop1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYaJbBll3C7F8IzZJR2im6CM9j7A2oeU

1.Display Fibonacci series up to 10 terms.
"""

n = 10

# first two terms
a = 0
b = 1

print("Fibonacci series up to", n, "terms:")

for i in range(n):
    print(a, end=" ")
    c = a + b
    a = b
    b = c

"""2. Find the factorial of a given number. Ask the user to provide the number.

"""

num = int(input("Enter a number: "))

# Initialize factorial
factorial = 1

# Check if number is negative
if num < 0:
    print("Factorial does not exist for negative numbers.")
elif num == 0:
    print("Factorial of 0 is 1")
else:
    for i in range(1, num + 1):
        factorial *= i
    print("Factorial of", num, "is", factorial)

"""3. Write a program to print a right angle triangle using the for loop.

"""

rows = 5

for i in range(1, rows + 1):
    for j in range(i):
        print("*", end=" ")
    print()

"""4. Make a simple calculator that can add, subtract, multiply and divide two numbers using function.

"""

# Function to add
def add(a, b):
    return a + b

# Function to subtract
def subtract(a, b):
    return a - b

# Function to multiply
def multiply(a, b):
    return a * b

# Function to divide
def divide(a, b):
    if b == 0:
        return "Cannot divide by zero"
    return a / b

# Ask user for input
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("Select operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

choice = input("Enter choice (1/2/3/4): ")

if choice == '1':
    print("Result =", add(num1, num2))
elif choice == '2':
    print("Result =", subtract(num1, num2))
elif choice == '3':
    print("Result =", multiply(num1, num2))
elif choice == '4':
    print("Result =", divide(num1, num2))
else:
    print("Invalid choice")

"""5. Remove the first duplicate element of a list

"""

lst = [1, 2, 3, 2, 4, 5, 3]

seen = set()

for i in range(len(lst)):
    if lst[i] in seen:
        lst.pop(i)
        break
    else:
        seen.add(lst[i])

print("List after removing first duplicate:", lst)

"""6. Write a Python program to create a new dictionary by extracting the mentioned keys from the below dictionary.
sample_dict = { "name": "Anderson", "age": 35, "salary": 5000, "city": "London"}
keys = ["name", "salary"]
Expected Output: {'name': 'Anderson', 'salary': 5000}
"""

sample_dict = {
    "name": "Anderson",
    "age": 35,
    "salary": 5000,
    "city": "London"
}

# Keys to extract
keys = ["name", "salary"]

# Create new dictionary
new_dict = {k: sample_dict[k] for k in keys}

print("New dictionary:", new_dict)

"""7. Write a Python program to convert two lists into a dictionary in a way that item from list_one is the key and item from list_two is the value.
list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]
Expected Output: {'one': 1, 'two': 2, 'three': 3}
"""

list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]

# Converting lists into dictionary
result = dict(zip(list_one, list_two))

print("Resulting dictionary:", result)