# -*- coding: utf-8 -*-
"""workshop2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPT8-ZQlXNzID2TUGdtybYI_6oWMEEQv

#1.1 Dataset Loading
"""

import pandas as pd

# Automatically load dataset
df = pd.read_csv("StudentPerformanceFactors.csv")

print("Dataset Loaded Successfully")
print(df.shape)

"""#2.1 Data Exploration"""

print(df.head())

"""#2.2 Dataset Information"""

print(df.info())

"""#2.3 Statistical Summary"""

print(df.describe())

"""#2.4 Checking Missing Values"""

print(df.isnull().sum())

"""#2.5 Data Visualization

##2.5.1 Distribution of Exam Scores
"""

import matplotlib.pyplot as plt

plt.hist(df["Exam_Score"], bins=30)
plt.title("Distribution of Exam Scores")
plt.xlabel("Exam Score")
plt.ylabel("Frequency")
plt.show()

"""##2.5.2 Hours Studied vs Exam Score"""

plt.scatter(df["Hours_Studied"], df["Exam_Score"])
plt.xlabel("Hours Studied")
plt.ylabel("Exam Score")
plt.title("Study Hours vs Exam Score")
plt.show()

"""##2.5.3 Attendance vs Exam Score"""

plt.scatter(df["Attendance"], df["Exam_Score"])
plt.xlabel("Attendance")
plt.ylabel("Exam Score")
plt.title("Attendance vs Exam Score")
plt.show()

"""#2.6 Data Transformation"""

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

"""#2.7 Correlation Analysis"""

import seaborn as sns

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Feature Correlation Matrix")
plt.show()